name: Build and Release Binaries

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build-matrix:
    name: Build ${{ matrix.platform }} Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x64
            extension: ''
            archive_ext: tar.gz
          - os: windows-latest
            platform: win-x64
            extension: '.exe'
            archive_ext: zip
          - os: macos-latest
            platform: osx-x64
            extension: ''
            archive_ext: tar.gz
          - os: macos-14
            platform: osx-arm64
            extension: ''
            archive_ext: tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential libc6-dev

      - name: Run comprehensive build script (Unix)
        if: runner.os != 'Windows'
        run: chmod +x scripts/build.sh && ./scripts/build.sh

      - name: Run comprehensive build script (Windows)
        if: runner.os == 'Windows'
        run: ./scripts/build.ps1
        shell: powershell

      - name: Run Tests
        # Dieser Schritt wird jetzt auf ALLEN Plattformen funktionieren.
        run: dotnet test --configuration Release

      - name: Publish GrepSQL Binary
        run: dotnet publish src/GrepSQL.CLI/GrepSQL/GrepSQL.csproj --configuration Release --runtime ${{ matrix.platform }} --self-contained true --output ./publish/${{ matrix.platform }} -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true

      - name: Test binary functionality (Unix)
        if: runner.os != 'Windows'
        run: |
          ./publish/${{ matrix.platform }}/GrepSQL.CLI${{ matrix.extension }} --help
          echo "SELECT * FROM users;" | ./publish/${{ matrix.platform }}/GrepSQL.CLI${{ matrix.extension }} "SelectStmt"

      - name: Test binary functionality (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          ./publish/${{ matrix.platform }}/GrepSQL.CLI${{ matrix.extension }} --help
          echo "SELECT * FROM users;" | ./publish/${{ matrix.platform }}/GrepSQL.CLI${{ matrix.extension }} "SelectStmt"

      - name: Create archive (Unix)
        if: matrix.archive_ext == 'tar.gz'
        run: |
          cd publish/${{ matrix.platform }}
          tar -czf ../../grepsql-${{ matrix.platform }}.tar.gz GrepSQL.CLI${{ matrix.extension }}
          cd ../..

      - name: Create archive (Windows)
        if: matrix.archive_ext == 'zip'
        run: |
          cd publish/${{ matrix.platform }}
          Compress-Archive -Path "GrepSQL.CLI${{ matrix.extension }}" -DestinationPath "../../grepsql-${{ matrix.platform }}.zip"
          cd ../..

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: grepsql-${{ matrix.platform }}
          path: |
            grepsql-${{ matrix.platform }}.*
            publish/${{ matrix.platform }}/GrepSQL.CLI${{ matrix.extension }}
          retention-days: 30

  create-release:
    name: Create Release
    needs: build-matrix
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (contains(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Prepare release assets
        run: |
          mkdir -p ./release-assets
          find ./artifacts -name "grepsql-*.tar.gz" -exec cp {} ./release-assets/ \;
          find ./artifacts -name "grepsql-*.zip" -exec cp {} ./release-assets/ \;
          echo "Release assets:"
          ls -la ./release-assets/

      - name: Get version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            VERSION="main-$(git rev-parse --short HEAD)"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "tag=main-build" >> $GITHUB_OUTPUT
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate release notes
        id: release_notes
        run: |
          if [[ "${{ steps.version.outputs.is_tag }}" == "true" ]]; then
            LAST_TAG=$(git describe --tags --abbrev=0 --exclude="${{ steps.version.outputs.tag }}" 2>/dev/null || echo "")
            if [ -z "$LAST_TAG" ]; then
              COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges)
            else
              COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s (%h)" --no-merges)
            fi
            
            cat > release_notes.md << EOF
          ## 🚀 GrepSQL v${{ steps.version.outputs.version }}
          A powerful command-line tool for searching and filtering SQL files using PostgreSQL AST patterns.
          ### 📦 Downloads
          Choose the appropriate binary for your platform:
          - **Linux (x64)**: \`grepsql-linux-x64.tar.gz\`
          - **macOS (Intel)**: \`grepsql-osx-x64.tar.gz\`
          - **macOS (Apple Silicon)**: \`grepsql-osx-arm64.tar.gz\`
          - **Windows (x64)**: \`grepsql-win-x64.zip\`
          ### 🚀 Quick Start
          \`\`\`bash
          # Extract the binary (example for Linux)
          tar -xzf grepsql-linux-x64.tar.gz
          # Make executable (Unix systems)
          chmod +x GrepSQL.CLI
          # Search for SELECT statements
          ./GrepSQL.CLI "SelectStmt" *.sql
          \`\`\`
          ### 📋 Changes in this release
          $COMMITS
          EOF
          else
            RECENT_COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges -10)
            cat > release_notes.md << EOF
          ## 🔧 Development Build - ${{ steps.version.outputs.version }}
          This is an automated build from the main branch. Use for testing purposes.
          ### 📦 Downloads
          - **Linux (x64)**: \`grepsql-linux-x64.tar.gz\`
          - **macOS (Intel)**: \`grepsql-osx-x64.tar.gz\`
          - **macOS (Apple Silicon)**: \`grepsql-osx-arm64.tar.gz\`
          - **Windows (x64)**: \`grepsql-win-x64.zip\`
          ### 📋 Recent changes
          $RECENT_COMMITS
          ### ⚠️ Note
          This is a development build. For stable releases, use the latest tagged version.
          EOF
          fi

      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.is_tag == 'true' && format('🚀 GrepSQL v{0}', steps.version.outputs.version) || format('🔧 Development Build - {0}', steps.version.outputs.version) }}
          body_path: release_notes.md
          files: ./release-assets/*
          draft: false
          prerelease: ${{ steps.version.outputs.is_tag == 'false' }}
          token: ${{ secrets.GITHUB_TOKEN }}